export interface Torsadage {
    id: number;
    plant : string ; 
    segment : number ; 
    numeroMachine : string ; 
    typeOperation : string ; 
    code: string;
    specificationMesure: string;
    date: string;
    heureCreation : string ; 
    numeroCycle: number;
    userTorsadage: number;
    moyenne: number;
    etendu: number;
    ech1: string;
    ech2: string;
    ech3: string;
    ech4: string;
    ech5: string;
    numCommande: number;
    quantiteTotale: number;
    numerofil: string;
    longueurFinalDebutCde: number;
    longueurFinalFinCde: number;
    longueurBoutDebutCdeC1: number;
    longueurBoutDebutCdeC2: number;
    longueurBoutFinCdeC1: number;
    longueurBoutFinCdeC2: number;
    decalageMaxDebutCdec1: number;
    decalageMaxDebutCdec2: number;
    decalageMaxFinCdec1: number;
    decalageMaxFinCdec2: number;
    quantiteAtteint: number;
    matriculeAgentQualite: number;
    decision: number;
    rempliePlanAction: number;
    pdekId : number ;
    numPage : number ; 
    sectionFil : string ; 
  }
  